### ISSUE TITLE
HI,someshting wrong about the package?

### ISSUE THREAD

**Issue by arick-001** [Naereen/dot2tex#1]
import dot2tex as dt

  File "C:\ProgramData\Anaconda3\lib\site-packages\dot2tex\__init__.py", line 36, in <module>
    __version__ = d2t.__version__

AttributeError: module 'dot2tex' has no attribute '__version__'.
The problem with python 3.6?

**Comment by Naereen** [comment]
Hi,
I will try today.

**Comment by Naereen** [comment]
Hi,
I tried again on my Linux (XUbuntu) laptop with Python 3.6, no issue at all.

I don't have a Windows machine to try with, sorry, I cannot try more to help you.
