### ISSUE TITLE
--autosize does not work

### ISSUE THREAD

**Issue by Chimrod** [Naereen/dot2tex#2]
--autosize launch a latex subprocess and extract some informations from the latex log. 

But [the function](https://github.com/Naereen/dot2tex/blob/master/dot2tex/dot2tex.py#L69) does not let the process terminate before reading the log, which lead to the wrong message 

```
ERROR    No dimension data could be extracted from dot2tex.tex.
ERROR    Failed to preprocess the graph.
Is the preview LaTeX package installed? ((Debian package preview-latex-style)
To see what happened, run dot2tex with the --debug option.
```

I did not make intensive tests but this code seems to work 

```python
    def os_popen(command):
        # pipe = os.popen("cmd", 'r', bufsize) ==>
        proc = Popen(command, shell=True, stdout=PIPE)
        proc.wait()
        return proc.stdout
```

**Comment by Naereen** [comment]
Hi, thanks for reporting the issue!
Have you checked that the `preview` latex is installed?
I tried your fix, it looks nice on paper but for the code I'm not sure that's the solution, in the tests I'm getting lots of warning
```bash
$ python test_dot2tex.py
...
subprocess.py:766: ResourceWarning: subprocess 28924 is still running
```

**Comment by Chimrod** [comment]
Hello, thanks for answering so fast ! Yes, I've checked that preview package is installed. I did not understand the error at first time. Without the patch, here is the output in dot2tex.log : 

```
2018-03-21 17:04:03,677 dot2tex DEBUG Running command: latex -interaction=nonstopmode /tmp/dot2texrc35_9tp/dot2tex.tex
2018-03-21 17:04:03,738 dot2tex DEBUG errcode: None
2018-03-21 17:04:03,739 dot2tex DEBUG Unable to open log file /tmp/dot2texrc35_9tp/dot2tex.log
2018-03-21 17:04:03,739 dot2tex DEBUG Texdimdata: []
2018-03-21 17:04:03,739 dot2tex ERROR No dimension data could be extracted from dot2tex.tex.
2018-03-21 17:04:03,739 dot2tex ERROR Failed to preprocess the graph.
```

Once I've applied the patch, I got the expected output. I did not run the unit test, I've just run dot2tex with my dotfile with `dot2tex --autosize --debug indices.dot` (FYI I'm running python in a cygwin environment, but this should not be signifiant in this case)

**Comment by Naereen** [comment]
OK thanks for again for reporting and replying that fast -- and sorry for the delay.
I'll try again more to see why the tests are failing with your patch.

**Comment by Naereen** [comment]
It should be fixed now!

**Comment by Chimrod** [comment]
Thanks for giving some credits to my report and fix the bug 👍

**Comment by Naereen** [comment]
When you'll have time, please try again and let me know if the fix was enough.
Cheers

**Comment by Chimrod** [comment]
Hello, I've check the last version and it works perfectly !

Thanks for your correction

**Comment by Naereen** [comment]
Great!
